### ISSUE TITLE
Not getting unlocked status event

### ISSUE THREAD

**Issue by m0vse** [uhppoted/uhppoted-app-home-assistant#1]
Hi.

Well done for creating this, I realise some features are a bit rough, but I have been able to configure it for our building which has 3 floors with a controller on each floor. 

With all of the doors, I am able to unlock them using uhppoted.door.{door}.unlock and the uhppoted.door.{door}.lock status shows unlocked until the next poll. However the uhppoted.door.{door}.unlocked.event appears to never fire for any door and the status is always shown as Unknown. Any ideas? 

All of my controllers are V6.62.51215 which I realise is pretty old...

One other thing that would be good to know, is there anyway to import the existing swipe records from a controller?

Good work so far though.

Phil

**Comment by m0vse** [comment]
To update this, after a bit more research, it appears that 'some' doors are working and generating the unlocked events. Of our 9 doors, 3 seem to work. There seems to be no pattern though (different numbers doors on different controllers?)

**Comment by uhppoted** [comment]
Oh dear .. I guess this means I'm going to have to remove the bit in the README which says "_... probably not suitable for office buildings_" :-).

Hmm, v6.62.51215 firmware should be ok - it's the earliest version that is _known to work_, although it does have some oddities that were fixed in later versions. But I've just checked and the code is in place to handle those.

Oh .. oops! Best guess is that the controllers are probably not configured to send events to the _Home Assistant_ machine and _uhppoted-app-home-assistant_ doesn't configure them automatically either. I need to think about how best to do that - but if you want to configure them manually in the interim, the easiest is probably the [CLI](https://github.com/uhppoted/uhppote-cli) [_set-listener_](https://github.com/uhppoted/uhppote-cli?tab=readme-ov-file#set-listener) command:

```
set-listener <controller> <address:port>

e.g. uhppote-cli set-listener 405419896 192.168.1.100:60001
```

The reason you're seeing occasional events is that there is a background process that retrieves "missing" events from the controller, but the interaction with the _Home Assistant_ poll cycle and event handling makes it more than a bit unintuitive.

re. _existing swipe records._ It's possible except that I have no idea where to store them _Home Assistant_ (am open to suggestions though). I did experiment a bit but _hass_ timestamps events when it receives them so the built-in event logs make no sense whatever doing it that way.

**Comment by m0vse** [comment]
Perfect, set-listener has sorted it! I assume the controllers only send an unlock event as the doors show as unlocked until the next poll (30 seconds) is this correct?

I was a bit concerned about using 'early Alpha' software but since the Windows software stopped working, I have been managing them manually using the internal web interface on each controller, which is a bit painful, so I thought even if it is only 1/2 working, it must be better than that!

I assume the set-listener setting is persistent on the controllers (or do I need to set it again after a controller reboot?) 

I will have a think about the existing swipe records, but I am a bit new to HA so still learning.

Thanks again

Phil

**Comment by uhppoted** [comment]
Oh **great**!! Very glad it was that and not something completely weird, and yes, you're completely correct - the controller only generates an _unlocked_ event, the _locked_ event is a synthetic event that is generated from the poll data. 

The controller event listener setting is persistent across power cycles, etc, so it only needs to be set once - although I may add a `controller-unconfigured` event/entity/somesuch so that at least there is some kind of notification if it isn't set. Still  thinking about how best to do it though...

re. _early Alpha._ &lt;smile&gt; I shall try not to break anything.

re. _I am a bit new to HA so still learning_. Likewise - it's been quite a learning curve :-) 

I'm going to leave this issue open until I have something in place to set/monitor the controller event listener setting - will post an update here when it's available.

**Comment by uhppoted** [comment]
Hi,

The wording of the log message is a bit misleading - it is updating the _Home Assistant_ controller date/time entity with the controller date/time every 30 seconds (or whatever poll interval you choose to configure). The actual controller date/time is only set when you change it via the _uhppoted.controller.{controller}.datetime_ entity. I'll fix the log message to read something like _"fetching controller date/time"_ to avoid confusion.

re. _who/what/when_. The controller doesn't natively support access queries because it's only a small microcontroller with limited capability. It's also reasonably unlikely that the _Home Assistant_ custom component ever will - _hass_ just doesn't include the UI elements to implement something like that (at least not at the moment anyway).

A tool to query and analyse the event logs is on the TODO list but it's not going to happen anytime soon barring a 3AM stroke of genius - it is surprisingly complicated and difficult to do well! In the interim however, there are a couple of other other options:

- use the _CLI_ [`get-event`](https://github.com/uhppoted/uhppote-cli#get-event) command to retrieve events from the controllers and store them in a database that you can query on an ad hoc basis. There is a cookbook example of how to do that using a bash script and _sqlite3_ [here](https://github.com/uhppoted/uhppoted/tree/master/cookbook/get-events). 

- [uhppoted-app-db](https://github.com/uhppoted/uhppoted-app-db) has a [`get-events`](https://github.com/uhppoted/uhppoted-app-db#get-events) command which does the same thing but with a whole lot less fuss. You just need to schedule the command to run every 30 minutes or so to fetch events to the DB of your choice.

- [uhppoted-httpd](https://github.com/uhppoted/uhppoted-httpd) can display a user friendly view of the event log - although going by the version of your controllers you're going to have a **lot** of events which translates to a lot of scrolling. You're also not going to be able to run _httpd_ and the _Home Assistant_ custom component concurrently (well, you can but it's complicated and not recommended)

**Comment by uhppoted** [comment]
Hi,

I'm going to close this out - the latest alpha release includes the ability to configure the destination address for controller events and will set it automatically if it is incorrect.

Thanks for braving the early alpha release :-)
