### ISSUE TITLE
Adding controller not discoverable due to firewall settings?

### ISSUE THREAD

**Issue by YBonline** [uhppoted/uhppoted-app-home-assistant#3]
Glad to see Home Assistant integration arriving! This looks absolutely amazing!

I was trying to get this going, but due to my network configuration (for security reasons), discovery of the controllers is not discoverable over the network, but they are accessible directly by the IP address. Is there any way to manually add a controller by specifying an IP address?

**Comment by uhppoted** [comment]
I was **just** writing up the release notes which include "_... only supports controllers on the local LAN_" :-).

Unfortunately, at the moment it's not possible to use controllers that aren't discoverable because the underlying Python library currently only supports UDP broadcast. It's probably the very first thing I'm going to fix once this release is out, but it is still going to take a little while because it's a fair amount of work.

For the interim, it **should** be possible to work around the limitation using [uhppoted-tunnel](https://github.com/uhppoted/uhppoted-tunnel) to forward the UDP packets but that may be messier and/or more complex than you would like (and also I haven't tried it) so it might be better just to wait a bit.

**Comment by uhppoted** [comment]
- [ ] Add support for UDP::send to _uhppoted-python_
- [ ] Allow configuration of off-LAN controllers in configuration.yaml
- [ ] Include off-LAN controllers in _discovered_ controllers list
- [ ] Use UDP::send for off-LAN controllers

**Comment by uhppoted** [comment]
Hi,

Just a quick update - _v0.8.8.1_ with support for off LAN controllers has been [released](https://github.com/uhppoted/uhppoted-app-home-assistant/releases).

The instructions for configuring off LAN controllers are [here](https://github.com/uhppoted/uhppoted-app-home-assistant?tab=readme-ov-file#off-lan-controllers), but basically - add them to the _configuration.yaml_ file and they will be included in the discovered controllers list when you create a new _uhppoted_ entry or run _Configure_ on an existing entry:
```
...
uhppoted:
    ...
    controllers:
        - 
            controller: 504030201
            address: 192.168.1.100
        - 
            controller: 605040302
            address: 192.168.1.100
            port: 60000
        - 
            controller: 706050403
            address: 192.168.1.100
            port: 54321
            timeout: 0.56
...
```

I'll leave this issue open for a couple of days in case you pick up any major problems.

**Comment by uhppoted** [comment]
Hi YB, think this is basically done so going to close this and move on to the next thing - feel free to reopen it if you need to.

**Comment by YBonline** [comment]
Hey, didn't get a chance to try this until now but just figured I'd update that it worked great, no issues at all! Thank you again!

**Comment by uhppoted** [comment]
Oh great! Thanks for the update :-)

The next set of changes are going to be mostly internal restructuring and cleaning up to make it more manageable, etc so you won't be seeing much visible improvement but stuff is nonetheless happening.
